# This configuration is for the standalone version of blockbuilder-search.
# Used with netlify-cli tool
# https://www.netlify.com/docs/netlify-toml-reference/
[build]
  command = 'npm run parcel-build'
  publish = 'dist'

[dev]
  command = 'npm run parcel'
  port = 1234
  publish = "dist"

[[redirects]]
  from = "/api/*"
  to = "https://blockbuilder.org/api/:splat"
  status = 200
  force = true
