export default {
  REQUEST_SEARCH: "REQUEST_SEARCH",
  RECEIVE_SEARCH: "RECEIVE_SEARCH",
  REQUEST_PAGE: "REQUEST_PAGE",
  RECEIVE_PAGE: "RECEIVE_PAGE",
  RECEIVE_SCREENSHOTS: "RECEIVE_SCREENSHOTS",
  REQUEST_AGGREGATE_D3_API: "REQUEST_AGGREGATE_D3_API",
  RECEIVE_AGGREGATE_D3_API: "RECEIVE_AGGREGATE_D3_API",
  REQUEST_AGGREGATE_D3_MODULES: "REQUEST_AGGREGATE_D3_MODULES",
  RECEIVE_AGGREGATE_D3_MODULES: "RECEIVE_AGGREGATE_D3_MODULES",
  SET_QUERY: "SET_QUERY"
};
